defaults: &defaults
  working_directory: /tmp
  docker:
    - image: nwnxee/builder

version: 2
jobs:
  build-nwnxee:
    <<: *defaults
    steps:
      - run: mkdir -p workspace
      - run: cd workspace
      - checkout
      - run: CC="gcc -m32" CXX="g++ -m32" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
      - run: make all
      - persist_to_workspace:
        root: /tmp/workspace

  package-nwnxee:
    <<: *defaults
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run: cd /tmp/workspace
      - run: Scripts/packageNWScript.sh
      - store_artifacts:
          path: Binaries

      
workflows:
  version: 2

  build-deploy:
    jobs:
      - build-nwnxee:
#        filters:
#          tags:
#            only: /.*/
      - package-nwnxee:
        requires:
          - build-nwnxee        
#        filters:
#          tags:
#            only: /^build.*/
#        branches:
#          only: /master/
